services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: helpdesk_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - helpdesk_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://helpdesk_elasticsearch:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    entrypoint: ["/app/entrypoint.sh"]
    env_file:
      - .env          # put your STREAMLIT_* and other secrets here
    environment:
      # Point at the system CA bundle (now containing your two extra certs)
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      # If you use requests, you can also set REQUESTS_CA_BUNDLE:
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    ports:
      - "8501:8501"   # map host 8501 → container 8501
      - "8000:8000"   
    volumes:
      - ./:/app       # so you can code locally and see changes
    networks:
      - helpdesk_network

volumes:
  es_data:
    driver: local

networks:
  helpdesk_network:
    driver: bridge 