# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3Q6mFOJLDVsX2SbhOTSql_B9wVTYK_M
"""

!pip install -q groq sentence-transformers faiss-cpu pandas openpyxl

# 📂 3. Chargement des données
import pandas as pd

# Téléverse les fichiers via l’interface de Colab
emails_df = pd.read_excel("/content/emails_incidents_dataset (2).xlsx")
criteria_df = pd.read_excel("/content/Matrice P1  P2 détaillée.xlsx")

# Extraction des emails (ajuste si la colonne a un nom différent)
emails = emails_df['email'].dropna().tolist()

# 🧠 4. Embedding avec sentence-transformers et indexation FAISS
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
email_embeddings = model.encode(emails, show_progress_bar=True)

dimension = email_embeddings.shape[1]
faiss_index = faiss.IndexFlatL2(dimension)
faiss_index.add(np.array(email_embeddings))

print("📌 Colonnes disponibles dans le fichier :", emails_df.columns.tolist())

from groq import Groq

client = Groq(api_key="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")

models = client.models.list()

for model in models.data:
    print(model.id)

"""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


"""

# ✅ INSTALLATION
!pip install -q sentence-transformers groq pandas

# ✅ IMPORTS
from sentence_transformers import SentenceTransformer
import pandas as pd
import groq
import os

# ✅ CONFIG
os.environ["GROQ_API_KEY"] = "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"  # 🔑 Remplacer par ta vraie clé
groq_client = groq.Groq(api_key=os.environ["GROQ_API_KEY"])

# ✅ MODEL MAPPING
model_map = {
    "LLaMA3-70B": "llama3-70b-8192",
    "gemma2-9b-it": "gemma2-9b-it",  # Confirmed name from Groq docs
    "qwen-qwq-32b": "qwen-qwq-32b"
}

responses = {friendly_name: [] for friendly_name in model_map.keys()}

# ✅ EMAILS
emails = [
    "Bonjour, nous avons une panne totale du système de billetterie à la gare de Lyon. Aucun ticket ne peut être émis. Merci d'agir rapidement.",
    "Salam, le WIFI est très instable dans la salle de pause du personnel à la gare de Marseille. Pouvez-vous vérifier cela avec l'opérateur ?",
    "Bonjour, nous avons reçu une alerte concernant une surcharge électrique dans la salle serveur du centre de gestion. Veuillez traiter cela comme prioritaire."
]

# ✅ EMBEDDINGS
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
embeddings = model.encode(emails)

# ✅ PROMPT FUNCTION
def build_prompt(email):
    return f"""
Tu es un expert dans l’analyse d’incidents informatiques. Voici un email utilisateur :

"{email}"

1. Est-ce un incident ? (Réponds par OUI ou NON)
2. Si oui, indique :
   - L’établissement ou gare concernée
   - Le groupe d’affectation ou prestataire
   - La priorité (P1 ou P2)
3. Si le message est incomplet, propose des informations complémentaires à demander.
Donne la réponse sous forme d’analyse claire.
"""

# ✅ ANALYSE
for email in emails:
    prompt = build_prompt(email)
    for friendly_name, model_id in model_map.items():
        try:
            response = groq_client.chat.completions.create(
                model=model_id,
                messages=[{"role": "user", "content": prompt}]
            )
            responses[friendly_name].append(response.choices[0].message.content.strip())
        except Exception as e:
            responses[friendly_name].append(f"Erreur : {e}")

# ✅ DISPLAY RESULTS
df = pd.DataFrame({
    "Email": emails,
    "LLaMA3-70B_Analysis": responses["LLaMA3-70B"],
    "Gemma-9B_Analysis": responses["gemma2-9b-it"],
    "Qwen-QWQ-32B_Analysis": responses["qwen-qwq-32b"]
})

pd.set_option("display.max_colwidth", None)
print(df)